// Edit menu items and prices from this single file.
// Prices in Indian Rupees (₹).

export const CATEGORIES = [
  { id: 'burgers', name: 'Burgers', emoji: '🍔' },
  { id: 'pizza', name: 'Pizza (S | M)', emoji: '🍕' },
  { id: 'wrap', name: 'Wrap', emoji: '🌯' },
  { id: 'chicken-sides', name: 'Chicken Sides', emoji: '🍗' },
  { id: 'chicken-momos', name: 'Chicken Momos', emoji: '🥟' },
  { id: 'sandwich', name: 'Veg & Non Veg Sandwich', emoji: '🥪' },
  { id: 'fries', name: 'French Fries', emoji: '🍟' },
  { id: 'refreshing-drinks', name: 'Refreshing Drinks', emoji: '🍹' },
  { id: 'combo-masti', name: 'Combo Masti', emoji: '🥤' },
];

export const MENU = [
  // BURGERS
  {
    id: 'b1',
    category: 'burgers',
    name: 'Veg Patty Burger',
    price: 59,
    veg: true,
    desc: 'Crispy seasoned vegetable patty, fresh crisp lettuce, and signature Mezbaan sauce in a soft toasted sesame bun.',
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'b2',
    category: 'burgers',
    name: 'Paneer Burger',
    price: 79,
    veg: true,
    desc: 'Golden crunchy paneer patty layered with fresh veggies, herbs, and tangy spiced mayonnaise.',
    image: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'b3',
    category: 'burgers',
    name: 'Chicken Patty Burger',
    price: 89,
    veg: false,
    desc: 'Tender spiced chicken patty, fresh salad leaves, melted slice, and creamy house dressing.',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'b4',
    category: 'burgers',
    name: 'Chicken Zinger Burger',
    price: 99,
    veg: false,
    desc: 'Fiery spiced, extra-crunchy chicken zinger fillet with fresh lettuce and special burger sauce.',
    popular: true,
    variants: [
      { name: 'Medium (M)', price: 99 },
      { name: 'Large (L)', price: 130 },
    ],
    image: 'https://images.unsplash.com/photo-1625813506062-0aeb1d7a094b?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'b5',
    category: 'burgers',
    name: 'American Chicken Hot Burger',
    price: 130,
    veg: false,
    desc: 'Bold American-style spicy chicken patty loaded with hot sauce, cheese, and crunchy pickles.',
    variants: [
      { name: 'Medium (M)', price: 130 },
      { name: 'Large (L)', price: 140 },
    ],
    image: 'https://images.unsplash.com/photo-1572802419224-296b0aeee0d9?auto=format&fit=crop&w=800&q=80',
  },

  // PIZZA (S | M)
  {
    id: 'p1',
    category: 'pizza',
    name: 'Veg Classic Corn & Cheese Pizza',
    price: 99,
    veg: true,
    desc: 'Golden sweet corn & rich creamy cheese baked to perfection on a freshly made crust.',
    variants: [
      { name: 'Small (S)', price: 99 },
      { name: 'Medium (M)', price: 149 },
    ],
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'p2',
    category: 'pizza',
    name: 'Farmhouse Delight Pizza',
    price: 119,
    veg: true,
    desc: 'Fresh vegetables, sliced olives, crisp capsicum & sweet corn loaded with gourmet cheese blend.',
    variants: [
      { name: 'Small (S)', price: 119 },
      { name: 'Medium (M)', price: 169 },
    ],
    image: 'https://images.unsplash.com/photo-1604382355076-af4b0eb60143?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'p3',
    category: 'pizza',
    name: 'Mezbaan Royal Paneer Pizza',
    price: 129,
    veg: true,
    desc: 'Soft marinated paneer cubes with fresh garden veggies & rich aromatic mozzarella.',
    variants: [
      { name: 'Small (S)', price: 129 },
      { name: 'Medium (M)', price: 189 },
    ],
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'p4',
    category: 'pizza',
    name: 'Mezbaan Tandoori Pizza',
    price: 179,
    veg: false,
    desc: 'Smoky tandoori chicken, red onion, green capsicum & loaded cheese on a fluffy crust.',
    popular: true,
    variants: [
      { name: 'Small (S)', price: 179 },
      { name: 'Medium (M)', price: 249 },
    ],
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'p5',
    category: 'pizza',
    name: 'Mezbaan Loaded Chicken Feast Pizza',
    price: 219,
    veg: false,
    desc: 'Extra chicken chunks + extra molten cheese pull for true chicken lovers.',
    popular: true,
    variants: [
      { name: 'Small (S)', price: 219 },
      { name: 'Medium (M)', price: 299 },
    ],
    image: 'https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?auto=format&fit=crop&w=800&q=80',
  },

  // WRAP
  {
    id: 'w1',
    category: 'wrap',
    name: 'Chicken Wrap',
    price: 79,
    veg: false,
    desc: 'Succulent spiced chicken, crisp shredded veggies, and creamy pepper sauce rolled in a warm tortilla.',
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'w2',
    category: 'wrap',
    name: 'Chicken Cheesy Wrap',
    price: 89,
    veg: false,
    desc: 'Juicy chicken tossed with melted cheddar cheese and house signature sauce in a toasted roll.',
    image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'w3',
    category: 'wrap',
    name: 'American Chicken Hot Cheesy Wrap',
    price: 99,
    veg: false,
    desc: 'Spicy American chicken chunks, jalapeños, molten cheese sauce, and chili relish rolled crisp.',
    popular: true,
    image: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&w=800&q=80',
  },

  // CHICKEN SIDES
  {
    id: 'cs1',
    category: 'chicken-sides',
    name: 'Chicken Popcorn (10 Pcs)',
    price: 99,
    veg: false,
    desc: 'Bite-sized tender chicken nuggets fried to crunchy perfection served with dipping sauce.',
    image: 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'cs2',
    category: 'chicken-sides',
    name: 'Chicken Wings (10 Pcs)',
    price: 119,
    veg: false,
    desc: 'Crispy glazed fried chicken wings coated in hot savory spiced sauce.',
    popular: true,
    image: 'https://images.unsplash.com/photo-1527477396000-e27163b481c2?auto=format&fit=crop&w=800&q=80',
  },

  // CHICKEN MOMOS
  {
    id: 'cm1',
    category: 'chicken-momos',
    name: 'Mezbaan Chicken Kurkure Momos (6 Pcs)',
    price: 100,
    veg: false,
    desc: 'Crispy outside, juicy inside. Packed with flavor, served hot with spicy momo chutney.',
    popular: true,
    image: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?auto=format&fit=crop&w=800&q=80',
  },

  // VEG & NON VEG SANDWICH
  {
    id: 'sw1',
    category: 'sandwich',
    name: 'Classic Veg Sandwich',
    price: 70,
    veg: true,
    desc: 'Fresh cucumber, ripe tomatoes, onion, and herb-mint chutney in grilled brown/white bread.',
    image: 'https://images.unsplash.com/photo-1525059696034-4967a8e1dca2?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'sw2',
    category: 'sandwich',
    name: 'Veg Cheese Sandwich',
    price: 90,
    veg: true,
    desc: 'Loaded melted cheese, crunchy veggies, Italian seasoning, and creamy spread grilled crisp.',
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'sw3',
    category: 'sandwich',
    name: 'Chicken Grill Sandwich',
    price: 90,
    veg: false,
    desc: 'Succulent grilled chicken shreds, pepper mayo, and fresh seasoning between golden pressed slices.',
    image: 'https://images.unsplash.com/photo-1553909489-cd47e0907980?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'sw4',
    category: 'sandwich',
    name: 'Chicken Tandoori Sandwich',
    price: 100,
    veg: false,
    desc: 'Charcoal-spiced tandoori chicken, diced onion, and creamy tandoori mayo grilled hot.',
    popular: true,
    image: 'https://images.unsplash.com/photo-1481070414801-51fd732d7184?auto=format&fit=crop&w=800&q=80',
  },

  // FRENCH FRIES
  {
    id: 'f1',
    category: 'fries',
    name: 'Salted French Fries',
    price: 50,
    veg: true,
    desc: 'Classic golden fries, salted and fried crisp outside with a fluffy interior.',
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'f2',
    category: 'fries',
    name: 'Peri Peri Fries',
    price: 60,
    veg: true,
    desc: 'Crisp golden fries thoroughly dusted with zesty, fiery peri peri spice mix.',
    image: 'https://images.unsplash.com/photo-1630384060421-cb20d0e0649d?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'f3',
    category: 'fries',
    name: 'Loaded Fries',
    price: 70,
    veg: true,
    desc: 'Crispy fries smothered in melted cheese sauce, tangy dressing, and seasoning.',
    image: 'https://images.unsplash.com/photo-1585109649139-366815a0d713?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'f4',
    category: 'fries',
    name: 'Chicken Loaded Fries',
    price: 120,
    veg: false,
    desc: 'Hot golden fries topped with juicy seasoned chicken chunks, jalapeños & molten cheese.',
    popular: true,
    image: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?auto=format&fit=crop&w=800&q=80',
  },

  // REFRESHING DRINKS
  {
    id: 'rd1',
    category: 'refreshing-drinks',
    name: 'Black Current Mojito',
    price: 99,
    veg: true,
    desc: 'Chilled sparkling black currant cooler infused with crushed mint leaves, lime, and ice.',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'rd2',
    category: 'refreshing-drinks',
    name: 'Blueberry Mojito',
    price: 119,
    veg: true,
    desc: 'Fresh iced blueberry soda muddled with zesty lime wedges and garden-fresh mint.',
    popular: true,
    image: 'https://images.unsplash.com/photo-1556881286-fc6915169721?auto=format&fit=crop&w=800&q=80',
  },

  // COMBO MASTI
  {
    id: 'c1',
    category: 'combo-masti',
    name: 'Chicken Loaded Feast Pizza + Fries + Drink',
    price: 349,
    veg: false,
    desc: 'Ultimate value feast: Chicken Loaded Feast Pizza served with crispy golden fries and a chilled soft drink.',
    popular: true,
    image: 'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?auto=format&fit=crop&w=800&q=80',
  },
];

export const BRAND = {
  name: 'Mezbaan',
  tagline: 'Freshly Crafted. Honestly Served.',
  address: 'Abul Fazal Enclave, Jamia Nagar, New Delhi',
  phone: '+91 8595244548',
  phoneRaw: '918595244548',
  email: 'contact@mezbaaan.in',
  website: 'mezbaaan.in',
  freeDeliveryMin: 300,
};
